@echo off
setlocal EnableDelayedExpansion
set cheese="ACKAWI" "ASADERO" "ASIAGO" "BABY-SWISS" "BAKERS-CHEESE" "BALADI" "BASKET-CHEESE" "BREAKFAST-CHEESE" "BRIE" "BRIE(TRIPLE-CRÈME)" "CAMEMBERT" "CARMODY" "CHANTALENO" "CHEDDAR" "CHEDDAR(RAW-MILK)" "COLBY" "COLBY/JACK" "COTIJA" "COTIJA(QUESO-ANEJO)" "COTTAGE-CHEESE(FARMER’S-CHEESE)" "CREAM-CHEESE" "CRESCENZA" "CURD" "DRY-JACK-EDAM" "ENCHILADO" "ENCHILADO" "ANEJO" "FETA" "FOLDED-CHEESE" "FONTINA" "FROMAGE-BLANC" "FRYING-CHEESE" "GOUDA" "GOUDA(RAW-MILK)" "HAVARTI" "LONGHORN" "MANCHEGO" "MARBLE" "CHEDDAR" "MASCARPONE" "MENONITA" "MONTEREY-JACK-MOZZARELLA(LOW-MOISTURE,PART-SKIM)" "MOZZARELLA(WATER-PACKED)" "OAXACA" "PANELA" "PORT-SALUT(ALSO-PORT-DU-SALUT-OR-ST.-PAULIN)" "PROVOLONE" "QUARK" "QUESO-BLANCO" "QUESO-BLANCO-FRESCO(QUESO-PARA-FRIER)" "QUESO-BLANCO-FRESCO(QUESO-PARA-FRIER)-&-QUESO-FRESCO-QUESO-FRESCO-REQUESON" "RICOTTA" "ROMANO" "SCAMORZA" "SCHLOSS" "ST.GEORGE" "STRING" "SYRIAN(ARMENIAN-STRING)" "TELEME"

color a
cls

set len=0 
set id=0
(for %%a in (%cheese%) do ( 
   set cheeses[!id!] = %%a
   set /A id=!id!+1
   echo %%a
))

:Loop
if defined cheeses[!len!] ( 
set /A len+=1
GOTO :Loop 
)
echo The length of the array is %len%